using System;

namespace GhostCore.Numerics
{
    /// <inheritdoc />
    /// <remarks>
    /// This field will get values generated by a function given in the ctor.
    /// Use it to create composite fields or other procedurally generated fields.
    /// </remarks>
    public class FunctionField<T> : Field<T> where T : struct
    {
        private readonly Func<float, float, float, T> _func;

        /// <summary>
        /// Creates an instance of a <see cref="FunctionField{T}"/> object.
        /// </summary>
        /// <param name="func">The function that will be called within the <see cref="GetValue(float, float, float)"/> method.</param>
        public FunctionField(Func<float, float, float, T> func)
        {
            _func = func;
        }

        /// <inheritdoc />
        public override T GetValue(float x, float y, float z)
        {
            return _func(x, y, z);
        }
    }
}